# Site settings
title: LaudOak 
email: laudoak@qq.com

url: "https://laudoak.github.io" 
github_username: LaudOak
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
#viewsourceroot: https://github.com/LiXizhi/LiXizhi.github.io/blob/master/
# this is the url root of the create page link on the footer page.
#newsourceroot: https://github.com/LiXizhi/LiXizhi.github.io/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: lixizhi
#disqus_url: "http://lixizhi.github.io"
#########################################

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge 

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
