# Site settings
title: 🚌 LaudOak
email: laudoak@gmail.com
description: 
github_username: LaudOak
permalink: /:year/:month/:day/:title/
new_post_source_root: https://github.com/LaudOak/laudoak.github.io/new/master
disqus_shortname: laudoak
disqus_url: "https://laudoak.github.io"
markdown: kramdown
